### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by Javed-Shahbaz** [LarryIVC/ToDoList-webpack#5]
## Hi Larry Villegas

@Javed-Shahbaz:
- Great job so far. 👍
- Please put all JavaScript files in a folder name module except index.js.

@federicaulzurrun:
- I suggest you add comment to your code for understanding of others. 
- Check again the JavaScript good practices for mor information.

@abiola-arobieke:
- Please apply DRY method to your style.css. For example, you have you have display flex in so many places. You could have defined it in just one place.

**Comment by LarryIVC** [comment]
@Javed-Shahbaz , @federicaulzurrun, @abiola-arobieke:
Thank you very much for your contributions, they will be implemented.
